# Generated by Django 2.2.15 on 2020-08-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200820_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body12345',
            new_name='body',
        ),
    ]
